spring:
  application:
    name: langa-backend
  data:
    mongodb:
      uri: mongodb://localhost:27017/langa_db
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
application:
  base-url: ${BASE_URL}
  persistence:
    provider: mongo
  security:
    jwt.secret: ${JWT_KEY}
    jwt.kid: ${JWT_KID}
    jwt.expiration: ${JWT_EXPIRATION}
    jwt.refresh-token.expiration: ${JWT_REFRESH_TOKEN_EXPIRATION}
    endpoints:
      unsecured:
        - /api/auth/**
        - /api/ingestion/**
        - /api/team-invitations/**
        - /api/first-connection**
        - /api/first-connection/**
    cors:
      allowed-origins:
        - http://localhost:3000
        - http://localhost:5173
      allowed-methods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
        - HEAD
      allowed-headers:
        - "*"
      allow-credentials: true
      pattern-registry: /**
  mail:
    provider: gmail
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    com.langa: DEBUG