spring:
    application:
        name: langa-backend
    data:
        mongodb:
            uri: mongodb://localhost:27017/langa_db
    mail:
      host: smtp.gmail.com
      port: 587
      username: ${MAIL_USERNAME}
      password: ${MAIL_PASSWORD}
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true
              required: true
application:
  persitence:
    provider: mongo
  security:
      jwt.secret: ${JWT_KEY}
      jwt.kid: ${JWT_KID}
      jwt.expiration: ${JWT_EXPIRATION}
      jwt.refresh-token.expiration: ${JWT_REFRESH_TOKEN_EXPIRATION}
  mail:
    provider: gmail
logging:
    level:
        org.springframework.web: DEBUG
        org.springframework.security: DEBUG
        com.langa: DEBUG