
# =============================================
# Langa Agent Sender Configuration
# =============================================

# Sender type: http or kafka
langa:
  sender:
    type: ${LANGA_SENDER_TYPE:http}

  # =============================================
  # HTTP Sender Configuration
  # =============================================
  http:
    url: ${LANGA_HTTP_URL:https://langa-production.up.railway.app/api/ingestion}

  # =============================================
  # Kafka Sender Configuration
  # =============================================
  kafka:
    bootstrap:
      server: ${LANGA_KAFKA_BOOTSTRAP_SERVER:localhost:9092}
    topic: ${LANGA_KAFKA_TOPIC:langa}
