name: Backend CI

on:
  push:
    branches: [ "main", "dev", "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '25'
          cache: 'maven'

      - name: Build and Test Agent
        run: mvn -B clean verify --file agent/pom.xml
      - name: Build and Test Backend
        run: mvn -B clean verify --file backend/pom.xml
